[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

## S{  まとめて囲む
[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'scrooloose/nerdtree'


#[[plugins]]
#repo = 'Shougo/unite.vim'
#
#[[plugins]]
#repo        = 'Shougo/neomru.vim'
#on_source   = ['unite.vim']

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'Townk/vim-autoclose'

[[plugins]]
repo = 'szw/vim-tags'


[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'tpope/vim-endwise'

#syntastic 構文チェック
[[plugins]]
repo = 'scrooloose/syntastic'

#status line (normal, ins, vis, replase)
[[plugins]]
repo = 'itchyny/lightline.vim'


#----------neosnippet--------------
#        <C-k> で使える
#----------------------------------
[[plugins]]
repo = 'Shougo/neocomplcache'
#snippet コード補完
[[plugins]]
repo = 'Shougo/neosnippet.vim'
#snippet 辞書
[[plugins]]
repo = 'Shougo/neosnippet-snippets'







#------------------------------------#
#      end dein setting TOML         #
#------------------------------------#




